name: CI

on:
  push:
    branches:
      - main
      - master
      # bors needs CI to trigger for pushes to its staging/trying branches
      - staging
      - trying
  pull_request:

env:
  RUSTFLAGS: -Cdebuginfo=0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly, 1.70.0]
    steps:
      - uses: actions/checkout@v4

      - name: set ${{ matrix.toolchain }} toolchain
        run: rustup override set ${{ matrix.toolchain }}

      # run tests
      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - run: cargo hack test --workspace --each-feature
        if: matrix.toolchain == 'nightly'
      - run: cargo hack test --workspace --each-feature --skip nightly
        if: matrix.toolchain != 'nightly'

  lints:
    name: "rustfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup override set nightly
          rustup component add rustfmt
        # rustup component add clippy
      - name: "fmt"
        run: cargo +nightly fmt --all -- --check
      #- name: "clippy"
      #  run: cargo +nightly clippy -Z unstable-options --workspace --all-targets --all-features


  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup override set nightly
          rustup component add miri
          cargo miri setup
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with Miri
        run: ./miri.sh
